name: Continues Integration
on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-dev:
    environment: Dev
    env:
      DB_USER_NAME: ${{ secrets.DB_USER_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      PORT: 3000
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Install Node and it's dependencies
        uses: ./.github/actions/cache-deps
      - name: Run Build
        run: npm run build
